### ISSUE TITLE
Implement access code support in Reservations

### ISSUE THREAD

**Issue by juyrjola** [City-of-Helsinki/respa#147]
Add field `Resource.access_code_type` as a CharField with only one choice for now: `pin6`. Other choices might be added in the future. If left `None`, access codes are not used for reservations to this resource. 

Add field `Reservation.access_code` as a CharField. API validates it based on `access_code_type`. If the field is left `null`, a random value is generated.

**Comment by akx** [comment]
My suggestion/clarifications:

* Add field `Resource.access_code_type` as a choiced CharField with these choices:
  * `none` - no access code required or generated; this is the default
  * `pin6` - generate a 6-digit numeric access code
  * (Other choices might be added in the future.)

* Add a field `Reservation.access_code` as a default-blank CharField of sufficient length.
* API consumers MAY, but are not required to, post `access_code` during Reservation creation.
  * If an access code is not posted but is required by the Resource, one is randomly generated according to the specified access code type.
  * If an access code is posted, it is validated based on the Resource's access code type's rules.
