### ISSUE TITLE
Implement management command for exporting translated fields into .xlsx

### ISSUE THREAD

**Issue by juyrjola** [City-of-Helsinki/respa#153]
The command should export data for all translated fields into an Excel file. See `munigeo/api.py:TranslatedModelSerializer` on how to figure out which fields are translated. `generate_reservation_xlsx` has code on writing Excel files for reference purposes.

The exporter should allow supplying the name of the model to export. Required models for now: Purpose, TermsOfUse, Resource.

**Comment by jussiarpalahti** [comment]
I give up.. Closing manually. This branch provides issue's feature

**Comment by jussiarpalahti** [comment]
Let's open so that PR merge could close this
