### ISSUE TITLE
Reservation datetime filtering is wonky

### ISSUE THREAD

**Issue by jussiarpalahti** [City-of-Helsinki/respa#157]
This works as it should:
https://api.hel.fi/respa/v1/reservation/?resource=aur3dq6tk7pq&start=2016-10-26T00:00:00%2B03:00&end=2016-10-27T16:30:00%2B03:00

This does something unspecified:
https://api.hel.fi/respa/v1/reservation/?resource%3Daur3dq6tk7pq%26begin%3D2016-10-26T00%3A00%3A00%2B03%3A00%26end%3D2016-10-26T16%3A30%3A00%2B03%3A00

Also, can't find datetime filtering in API docs

**Comment by jussiarpalahti** [comment]
Move from Arrow to iso8601 library to get better grasp on how this internet supplied string reading works.

**Comment by jussiarpalahti** [comment]
New information from user on gitter https://gitter.im/City-of-Helsinki/heldev?at=58c161ccdd08b4b859a8c07a

**Comment by cappe** [comment]
I also noticed that when my query is

> http://api.hel.fi/respa/v1/resource/avanulsil5fa/?start=2017-03-28&end=2017-03-29

the API returns the "available_hours" with the following elements:

> "available_hours": [
        {
            "ends": "2017-03-28T08:00:00+03:00",
            "starts": "2017-03-28T08:00:00+03:00"
        },
        {
            "ends": "2017-03-28T20:30:00+03:00",
            "starts": "2017-03-28T12:00:00+03:00"
        }
    ],

The first item doesn't really make sense since the "starts" equals "ends".

Also, the "opening_hours" returns the following:

> "opening_hours": [
        {
            "date": "2017-03-28",
            "opens": "2017-03-28T08:00:00+03:00",
            "closes": "2017-03-28T20:30:00+03:00"
        },
        {
            "date": "2017-03-29",
            "opens": null,
            "closes": null
        }
    ],

I've discussed about this issue before with jussiarpalahti but as a heads up for everyone else, it would make more sense to either include or exclude the end date, wheras in the current implementation the API returns null values for the excluded date as can be seen above. Whatever is decided, it would need documentation too.

Thanks!

**Comment by cappe** [comment]
Related to this, another query that returns "wonky" results:

> https://api.hel.fi/respa/v1/resource/au4avbls46bq/?start=2017-03-30&end=2017-03-31

returns

> "available_hours": [
        {
            "ends": "2017-03-30T08:00:00+03:00",
            "starts": "2017-03-30T08:00:00+03:00"
        },
        {
            "ends": "2017-03-30T09:00:00+03:00",
            "starts": "2017-03-30T08:30:00+03:00"
        },
        {
            "ends": "2017-03-30T11:00:00+03:00",
            "starts": "2017-03-30T10:30:00+03:00"
        },
        {
            "ends": "2017-03-30T13:00:00+03:00",
            "starts": "2017-03-30T13:00:00+03:00"
        },
        {
            "ends": "2017-03-30T13:30:00+03:00",
            "starts": "2017-03-30T15:00:00+03:00"
        },
        {
            "ends": "2017-03-30T15:00:00+03:00",
            "starts": "2017-03-30T15:00:00+03:00"
        },
        {
            "ends": "2017-03-30T17:00:00+03:00",
            "starts": "2017-03-30T17:00:00+03:00"
        },
        {
            "ends": "2017-03-30T20:30:00+03:00",
            "starts": "2017-03-30T18:30:00+03:00"
        }
    ],

Especially this: 

> {
            "ends": "2017-03-30T13:30:00+03:00",
            "starts": "2017-03-30T15:00:00+03:00"
},

The resource is available -1,5 hours which doesn't really make sense.

Cheers!
