### ISSUE TITLE
Make translations .xslx downloadable through an URL

### ISSUE THREAD

**Issue by juyrjola** [City-of-Helsinki/respa#160]
The path could be something like `/translations.xlsx`.

**Comment by jussiarpalahti** [comment]
This doesn't belong to DRF API though, does it? @juyrjola ?

I'm thinking adding it to resources.views

**Comment by jussiarpalahti** [comment]
Wasn't supposed to close this...

**Comment by jussiarpalahti** [comment]
Feature added to resources.views.translated_models_export and now usable through request to /translated_models @juyrjola
