### ISSUE TITLE
Admin action for running importers

### ISSUE THREAD

**Issue by jussiarpalahti** [City-of-Helsinki/respa#169]
At least sync operations for tprek and kirjastot.fi opening times

**Comment by petterill** [comment]
Would be great if these actions could be performed  in Django Admin.

**Comment by jussiarpalahti** [comment]
Oh. I made this issue 😳 

This is actually somewhat easy: https://docs.djangoproject.com/en/2.1/ref/contrib/admin/actions/
Something for next sprint perhaps.

Relevant management commands as per README:

```
python manage.py geo_import --municipalities finland
python manage.py geo_import --divisions helsinki
python manage.py resources_import --all tprek
python manage.py resources_import --all kirjastot
```

**Comment by JsseL** [comment]
You could indeed have an action that triggers a `call_command(...)` and then [redirect to a page that could show the output of the command](https://docs.djangoproject.com/en/2.1/ref/contrib/admin/actions/#actions-that-provide-intermediate-pages).
