### ISSUE TITLE
Convert uploaded resource image into either JPEG or PNG format

### ISSUE THREAD

**Issue by juyrjola** [City-of-Helsinki/respa#21]

**Comment by akx** [comment]
What input file formats do we accept? Or, say, anything that ImageMagick could handle?

**Comment by juyrjola** [comment]
Basically just the ones that Pillow handles. Photos should be JPEG, ground plans and maps should be PNG, but I'm not sure if it makes sense to enforce that.

**Comment by akx** [comment]
Okiedoke. Should we store the original file too, though, for possible later (re)conversion?

I assume the use case here is that the images the API outputs are "web usable"?

**Comment by juyrjola** [comment]
You can get the original image with the default image URL (such as here: http://api.hel.fi/respa/v1/resource/aurhijh62voa/).

You can request smaller images by appending ?dim=<width>x<height> to the image URL.

**Comment by akx** [comment]
The issue description seems to imply that images should be converted to JPEG/PNG upon ingestion/upload though (meaning that the original data uploaded would be lost)?

Or did I misunderstand things there?

**Comment by juyrjola** [comment]
Right. If the original image is not JPEG nor PNG, it should be converted. If it already is in either supported format, nothing should be done.

The `cropping` field contains user-specified information on how to crop the image into a square shape for thumbnails, but we're still undecided if we should support other aspect ratios than 1:1.
