### ISSUE TITLE
Implement linking resources

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/respa#294]
Users wants to book a room and a service/personnel associated with that room, for example a music studio & guide person for that. These calendars should be "linked" in some way, so that Varaamo knows which resources can be booked simultaneously.

Some specs here: https://docs.google.com/presentation/d/1Gzksr89GCPLspS-3WGAsUbCG65wzkTn6kvAsEulzcX0/edit?usp=sharing

**Comment by juyrjola** [comment]
Removing milestone because the UI changes will not be ready in time anyway.
