### ISSUE TITLE
Find if a specific time is free

### ISSUE THREAD

**Issue by jussiarpalahti** [City-of-Helsinki/respa#3]
## Tasks

 1. User has a specific time range (say 7.6.2015 12.00 - 14.00) to host a childrens' party at playground
 2. User asks for places that function as a playground and have free time on given range
 3. User receives a list of places

## Implementation

ToDo

**Comment by Rikuoja** [comment]
/v1/resource/?purpose=playground&duration=120&begin=2015-06-07T09:00+03:00&end=2015-06-07T11:00+03:00

**Comment by Rikuoja** [comment]
v1/available/?purpose=playground&duration=120&begin=2015-06-07T09:00+03:00&end=2015-06-07T11:00+03:00
