### ISSUE TITLE
As a user, I want to be informed why my reservation was cancelled

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/respa#313]
The reason for cancellation would be displayed for the user in the "notification cancelled" email. Requires a new text field for Respa, where this info can be stored.

This info would be filled in by staff when cancelling the reservation in Varaamo (requires changes in Varaamo UI).

**Comment by jussih** [comment]
Cancelling a reservation is done via HTTP DELETE call to the reservation URI. I thought for a while what would be the semantically correct way to add the cancellation message. Each has some downsides.

* Adding message data in the body of the DELETE call. While this is technically allowed by the HTTP specification it is not commonly done.
* Requiring a PUT or PATCH call to the reservation URI, setting the cancellation reason attribute. This semantically correct in REST, but might leave the data in a weird state if the PUT succeeds and the DELETE does not. The reservation would be active but still has a cancellation reason.
* Creating a new action URI for the reservation such as `/api/reservations/1/cancel/` which would take a POST with message data, set the reason and also set the state to canceled. This is a bit against the spirit of REST (delete with POST) and there would be 2 different locations for performing cancellation/deletion of a reservation.

Of these, I am leaning towards first updating the cancellation reason and then performing the DELETE.

**Comment by jussih** [comment]
The reservation can be set as cancelled also via normally PUTting a cancelled state.

Let's not touch the DELETE operation here, instead require cancelling a reservation via PUT with state and reason.

**Comment by jussih** [comment]
Some discussion around the implementation details:
- Simple solution:
Add a `cancellation_reason` text column to the reservation table. Varaamo does the cancellation via PUT with cancelled state and the user-provided string for the reason. The reason is sent in the notification mail to the user and can be displayed in Varaamo.

**Comment by petterill** [comment]
No translations. Staff decides the language he/she writes to the customer.
