### ISSUE TITLE
Implement outgoing email queuing / improve error handling

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/respa#327]
If Respa is unable to send notification email to the email API service provider, the resource booking process cannot be completed. In the case of the email API service account being suspended/closed and thus being unreachable, Respa pretty much dies.

Thus, there should be a queuing system for sending email OR somehow being unable to send email shouldn't kill the whole booking process.

**Comment by vikoivun** [comment]
As a concrete example, something like this: https://github.com/pinax/django-mailer
Nothing fancier shoud be needed as this is for error cases.
