### ISSUE TITLE
Add route to location link to email notification

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/respa#338]
The notification email should include a link to Palvelukartta that automatically displays a link to the Unit of the Resource that was booked. Similar thing is available on resource page on Varaamo for example https://varaamo.hel.ninja/resources/au2tzfwtc34q?date=2018-09-07 -> https://palvelukartta.hel.fi/unit/8215#!route-details. 

This requires that the Unit ID can be referenced in the email body. Currently only the name of the Unit can be referenced. The actual link to Palvelukartta will be constructed with html.

**Comment by juyrjola** [comment]
For the person who changes the email template: make sure the Unit comes from the `tprek` data source and split the string by `:` in Jinja.

**Comment by jussih** [comment]
There doesn't seem to be a split filter in Jinja, but one can use the replace filter to get rid of the tprek prefix :
 `{{ unit_id|replace("tprek:", "") }}`.
