### ISSUE TITLE
Fix max booking time input (Respa Admin UI)

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/respa#369]
Currently only 30min, 45min & 60 min are available for selection. Should be up to 10 hrs or so.

**Comment by petterill** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix max booking time input (Respa Admin)](https://trello.com/c/jGaeiOdE/27-fix-max-booking-time-input-respa-admin)

**Comment by otiala** [comment]
What kind of steps should be used?  And after 60 minutes, should we use hours instead?

My suggestion is below.

```
('00:30:00', '30 min'),
('00:45:00', '45 min'),
('01:00:00', '60 min'),
('02:00:00', '2 hr'),
('03:00:00', '3 hr'),
('04:00:00', '4 hr'),
('05:00:00', '5 hr'),
('06:00:00', '6 hr'),
('07:00:00', '7 hr'),
('08:00:00', '8 hr'),
('09:00:00', '9 hr'),
('10:00:00', '10 hr'),
```

**Comment by petterill** [comment]
Ideally, we would use some other kind of selection/input method, for example a free text field or some kind of counter, so that all these steps would not have to be defined separately. But as a quick fix, I agree with the suggestion by @otiala.
