### ISSUE TITLE
Implement support for "detailed instructions"

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/respa#378]
Support for instructions that describe how to use and access the resource. A new field that can be displayed in Varaamo and support for bringing this info to email notifications.

"Tilan käyttöön liittyvät erityiset ohjeet tarvittaessa, tähän tieto myös opastavan henkilökunnan läsnäolosta"

**Comment by petterill** [comment]
There seems to be a reservation_info field, check what this is used for at the moment and whether Varaamo utilizes it

**Comment by jussih** [comment]
Decision needed whether to use the existing `reservation_info` field for this or create a new attribute for Resource.

**Comment by petterill** [comment]
Let's go with a new attribute, since no one knows if `reservation_info` is used somewhere. Could be used for Huonevaraus, so let's not mess with it.

**Comment by juyrjola** [comment]
@petterill: could you then write a quick summary on what goes into `reservation_info` and what goes into the `instructions` (or whatever it's called) field? `reservation_info` is not used in Huonevaraus.
