### ISSUE TITLE
Fix Respa Admin opening hours

### ISSUE THREAD

**Issue by SamuelSaarentola** [City-of-Helsinki/respa#400]
Opening hours added through Respa Admin seem to be saved to the database but are not displayed in Varaamo. The saved opening hours can be viewed in Django Admin and Respa Admin. When saving them again in Django Admin, server error 500 occurs. So something goes wrong at some point. Investigate plz.

**Comment by jussih** [comment]
Root cause for this was found. Fix incoming.
