### ISSUE TITLE
Fix "sign in succesful" notification

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/respa#409]
Kirjauduttiin sisään käyttäjänä xxx should close when clicked on x (close). It does not currently close.

**Comment by otiala** [comment]
@petterill Does it require Helsinki account? Couldn't reproduce the notification with a regular Django admin account login.

**Comment by petterill** [comment]
@otiala probably, but you can test it with a google account for example. Log in with your account and PM me the username and I'll give you admin priviledges.
