### ISSUE TITLE
Cannot create a resource without unit although django admin allows it

### ISSUE THREAD

**Issue by turtommy** [City-of-Helsinki/respa#415]
Resource model has relation to Unit model which has blank=True and null=True attributes. This means a resource can be created without a unit but it causes an exception. This happens because resources method _update_opening_hours_ which is called during resource creation tries to access related units (which in this case is NoneType) 'periods' attribute.

> Exception Value:  'NoneType' object has no attribute 'periods'
> /var/www/respa/resources/models/resource.py in update_opening_hours, line 476

**Comment by petterill** [comment]
Make connecting a resource to Unit compulsory when creating resource. This should be fixed in the API, Django Admin & Respa Admin.

**Comment by jussih** [comment]
It was decided that we'll create a schema migration that makes the unit relation mandatory in database level. We need to create a data migration that can handle resource objects which have no unit set in the database. The proposed solution for the migration is 

1. check whether there are any resources with no unit
2a. if there was: create a Unit called "Orphan resources" and assign the orphans to this unit
2b. if there were none: no need to create new units

@juyrjola @jussiarpalahti Does this sound reasonable? In production there should be no unitless resources so no clutter will be created. In development environments the migration will create the Orphan unit to keep database integrity.
