### ISSUE TITLE
Update django-munigeo to newer release

### ISSUE THREAD

**Issue by jussiarpalahti** [City-of-Helsinki/respa#417]
Current version 0.2.0 is broken due to missing config file in packaging.

Newest release of the 0.2 branch or latest version is needed.

Required fix is in this release: https://github.com/City-of-Helsinki/django-munigeo/releases/tag/v0.2.4

**Comment by otiala** [comment]
Upgraded munigeo to 0.2.4 in PR #422 

@jussiarpalahti How was it actually broken, as in how can we confirm that the upgraded version is working?

**Comment by jussiarpalahti** [comment]
@otiala Importers fail on older version: https://github.com/City-of-Helsinki/respa#run-django-migrations-and-import-data
If all importers now work, then it's fixed!
