### ISSUE TITLE
Add "Lisäsisältö "varaus vahvistettu"-ilmoitukseen" field to Respa Admin in multiple languages

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/respa#435]

**Comment by otiala** [comment]
@petterill nähtävästi ko. ominaisuus on jo olemassa, vai ymmärsinkö jotain väärin?

![screenshot_2019-01-31 muokkaa resurssi grappelli](https://user-images.githubusercontent.com/44601448/52046553-a60c9f80-254f-11e9-9ddc-0f92fd11c708.png)
![screenshot_2019-01-31 respa admin -](https://user-images.githubusercontent.com/44601448/52046554-a60c9f80-254f-11e9-97e0-ee33af6ecd8f.png)
