### ISSUE TITLE
Add permission to view reservations for Manager role

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/respa#446]
Currently Managers cannot view reservations in Varaamo. Unit Group Administrators and Unit Administrators can view reservations. Managers should also be able to view the reservations of Units they manage.

See permission documentation https://github.com/City-of-Helsinki/respa/blob/master/docs/permissions.rst

**Comment by jussih** [comment]
From respa point of view all users should be able to see all reservations which are in either `CONFIRMED` or `REQUESTED` state. The only exception to this is that general managers can see _all_ reservations regardless of state. Unit group administrators or Unit administrators don't have special priviledges for viewing, only for modifying reservations.

Perhaps this limitation is on the UI side?

**Comment by petterill** [comment]
@jussih ok thanks for clearing that out. Seems to be a limitation of Varaamo then.
