### ISSUE TITLE
Fix displaying of days in opening hours section

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/respa#451]
When one creates a new time slot for opening hours (for example 5.2. - 8.2. tuesday to friday), the names of days are filled in correctly. However if one changes the dates (to for example 6.2. - 9.2. wednesday to saturday) the names of days remain the same. These should be updated to match the new dates correctly. The correct behaviour would be to always have the first day of the period first. If for example the period is 6.2. - 2.8.2., then the list would begin at tuesday and go through all the dates so that monday would be the last. This way it's probably less confusing to the user.

Also I guess it should not be possible to change the name of the date. For example one could change tuesday's name to wednesday. Is there any logic behind this?

**Comment by jussih** [comment]
It's actually possible to get day order completely randomized by changing the calendar inputs:
![screenshot from 2019-02-08 16-59-23](https://user-images.githubusercontent.com/668554/52487610-abf52700-2bc6-11e9-8040-1603d4975ce1.png)
