### ISSUE TITLE
Implement API-key authentication for URLs

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/respa#479]
API-key authentication is enabled for the reservation endpoint. Currently the token must be placed in the request header (Authorization: Token abcdef123456). 

Would be useful if it could be placed in the URL directly.

Also would be nice if inputting the API-key for swagger would work here https://dev.hel.fi/apis/respa/ (see if possible)

**Comment by petterill** [comment]
See also #510, this should be implemented there as well

**Comment by jussih** [comment]
Session authentication sounds like a good option.
