### ISSUE TITLE
Implement importing accessibility data from Accessibility API

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/respa#494]

**Comment by jussih** [comment]
The design decision here is what level of data do we save in Respa database and does Varaamo fetch any data independently from the Accessibility API.

The form and volume of data in the Accessibility API is complex, and it would be a lot of work to replicate all that in Respa.

One way to implement this without excessive duplication of effort would be as follows:
- Respa saves basic summary data for each Resource in it's database. This would be in general level such as "viewpoint: accessibility level", for example "I am a wheelchair user: red" meaning the resource is not wheelchair accessible. The Respa Resource API endpoint would allow filtering resources based on accessibility. For example list all resources where the viewpoint  "I am a wheelchair user" is green. 
- Varaamo implements a new search filter control using the new filter functionality.
- Respa saves a list of plain accessibility sentences for each Resource. These are exposed in the Resource detail data.
- Varaamo displays the list of sentences in the Resource detail page.

This would be reasonably simple to implement and would help the users a long way. In the future the Varaamo UI can develop a more comprehensive data browser for the Resource's particular accessibility details, accessing the Accessibility API directly without the need to replicate all the data in Respa.

From the Accessibility API we can get a list of Viewpoints. These would appear as choices in the UI for Resource searching. Each of these have 3 levels: green, red and unknown. 

```
  "I am a wheelchair user",
  "I am a wheelchair user - arrive by my car",
  "I am a wheelchair user - arrive with pick-up and drop-off traffic",
  "I have reduced mobility, but I walk",
  "I have reduced mobility, but I walk - arrive by my car",
  "I have reduced mobility, but I walk - arrive with pick-up and drop-off traffic",
  "I am a rollator user",
  "I am a rollator user - arrive by my car",
  "I am a rollator user - arrive with pick-up and drop-off traffic",
  "I am a stroller pusher",
  "I am visually impaired",
  "I am visually impaired - arrive with pick-up and drop-off traffic",
  "I use a hearing aid"
```

**Comment by petterill** [comment]
The only reason we want to import data from the accessibility API is for Varaamo users to be able to search for resources according to their accessibility. I think this level of detail for the search suggested by Jussi would at least be a good starting point. No point in duplicating all the data if Varaamo can utilize a hybrid model where some data is saved in Respa for search purposes and some more detailed data can be fetched from the accessibility API directly (if need be in the future).
