### ISSUE TITLE
Allow searching for reservations by reserver name and email

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/respa#496]
This should be allowed for staff users. Results should be limited according to user permissions, i.e. what unit each staff user is allowed to access.

**Comment by jussih** [comment]
Searching with reserver name seems to be already implemented. It is limited to users with the object-level permission `can_view_reservation_extra_fields` in each Resource individually.

Is this functionality ok? Should we just add the reserver email to the list of allowed search filters?

**Comment by petterill** [comment]
Good call! If the current model allows for staff to search for reservations by reserver name in Varaamo UI (when implemented) then this is enough. Have to check what permissions unit admins and unit managers have by default. What do you mean by "users having the permission in each resource individually" @jussih?

**Comment by jussih** [comment]
The permission is assignable via Units or Resource Groups in the admin UI:
![screenshot from 2019-03-05 14-27-53](https://user-images.githubusercontent.com/668554/53805782-c61aee80-3f53-11e9-9a9b-c4fef8fd19bb.png)

According to the permission docs (https://github.com/City-of-Helsinki/respa/blob/a16f02467c5135117415819088f2468d1ff3d552/docs/permissions.rst#resource-permissions) Unit admins and managers have this permission by default:
> General Administrators, Unit Group Administrator and Unit Administrators implicitly have all other resource permissions except ``can_approve_reservation`` for the resources in the Unit Group or Unit.

It seems that we just add the email as a new searchable field and this is done.
