### ISSUE TITLE
Find a free slot for a duration on a specific time range

### ISSUE THREAD

**Issue by jussiarpalahti** [City-of-Helsinki/respa#5]
## Tasks:

 1. User needs a studio to rehearse with a band for a two hour period on a time range of one week (6.6.2015-13.6.2015)
 2. User creates a query for places that function as a studio and have two free hours during given time range
 3. User receives a list of free places

## Implementation

Todo

**Comment by Rikuoja** [comment]
Query params: `/v1/resource/?purpose=play_with_band&duration=120&begin=2015-06-06T00:00+03:00&end=2015-06-14T00:00+03:00`

**Comment by Rikuoja** [comment]
Add `free_times` or something as an attribute in `resource` output.

**Comment by Rikuoja** [comment]
There are several options for returning the list of places:

1) Current implementation. The query returns available_hours for all resources for that purpose, including those with empty available_hours. This matches the default behavior of returning available_hours for the current day, if no period and duration are specified. This is needed for a standard listing of all resources.

2) Not listing resources that are not available in the period. The query filters resources according to duration and available_hours, if either are specified. However, if neither are specified, we must still list all the resources, not only those that are available on a given day.

Which one do you think is more logical?

**Comment by jussiarpalahti** [comment]
Can't we have another end point for these specific ease of use queries, like /query or something?

These could easily leverage regular end points' functionality, like available_hours, but with custom filtering, processing or what not? I'd rather not introduce any modality to end points. If you ask for units, resources or reservations, those you shall get, with support for some filtering.

To answer your specific point: number two on its own endpoints /query/available or /get/available. It would list units and their resources and the free time for these resources. I'd think this would solve the use case. It should thus support viewing as a calendar or on a map.

```
{ 2015-08-08: [
    { resource: Res1, 
      unit: Unit1,
      free: [ 
          { starts: 2015-08-08T12:00, ends: 2015-08-08T14:00}
          ...
      ]
}
```

**Comment by Rikuoja** [comment]
```
v1/available/?purpose=play_and_record_music&duration=120&begin=2015-06-06T00:00+03:00&end=2015-06-14T00:00+03:00
```

**Comment by juyrjola** [comment]
If it is resources that the API user wants, the endpoint should be `resource`. @Rikuoja's option 2 becomes a necessity with a growing number of resources. Whichever database schema is selected, it needs to support queries that return only the resources with available slots.
