### ISSUE TITLE
Fix period days ordering

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/respa#506]
If one creates a period, say from friday to sunday, then adds wednesday and thursday in there as well, they are added to the end of the list. Slightly confusing. Should be added as the first days in the list. See pic.

![sieppaa](https://user-images.githubusercontent.com/6796559/53887904-e8803b00-402b-11e9-8773-8be35d3a0c65.PNG)

**Comment by jussih** [comment]
This seems to be a bug. The implementation should follow the original specification, so when changing the start data from 5.4. to 3.4. the list of days should begin with the selected start date which is Wednesday.

**Comment by jussih** [comment]
I could not reproduce this yet.

* Created new period
* Set start date 5.4. and end date 7.4.
* Days are from Friday to Sunday
* Change start date to 3.4.
* Days are from Wednesday to Sunday

![screenshot from 2019-03-08 15-04-16](https://user-images.githubusercontent.com/668554/54030252-a5e96a80-41b3-11e9-84c9-9416edc0d268.png)
