### ISSUE TITLE
Fix hidden resources visible for admins and managers

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/respa#509]

**Comment by SamuelSaarentola** [comment]
Found few problems with this implemention.

Search page
- Both Unit Manager (UM) and Unit Admin(UA) can see hidden resource on search page, this is **working as intented.**

Resource page
- In resource page neither UM or UA can add this hidden resource to favorites, the button doesnt work.
- In resource page, the weekly reservation calendar is visually broken.
- by visually broken, they can only see opening hours only 1 of 7 days
- If either account tries to change the day from monthly calendar, they get empty results and when refreshing page (F5) both accounts encounter 404 page not found

My premises
- if UM or UA already has this hidden resource in their favorites, they can both see the resource correctly as well as opening hours for each day. **working as intented**
- Unit Manager is missing all of the staff permissions to make or view reservations
- UM has only user level permissions to the unit, see images.
- Without having to rewrite whole permissions levels to UM, Varaamo can still utilise this permission level to receptionist that needs to view the reserevation info about customers.
- **Add** UM rights to view reservation account information
![make a reservaion](https://user-images.githubusercontent.com/32957807/54019643-59426700-4194-11e9-9a72-199d30111620.png)
![reservation information](https://user-images.githubusercontent.com/32957807/54019644-59426700-4194-11e9-92ab-8dfbdb7840cc.png)
