### ISSUE TITLE
Add Unit name & Municipality to Resource details

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/respa#511]
Currently resource has Unit ID. Add Unit name and municipality there as well. This is quite handy when one makes a query for all resources as json and converts this to xlsx for analysis.

**Comment by juyrjola** [comment]
Note that adding fields to an API response will have a performance impact (due to added data to be serialized, transferred and deserialized). If certain clients require additional data, it's often good to include the data based on a query param (say, `include`).
