### ISSUE TITLE
Review Respa/Varaamo online payment

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/respa#523]
https://github.com/CityOfHameenlinna
https://github.com/City-of-Lappeenranta

Long reservations:
https://github.com/City-of-Helsinki/respa/compare/master...CityOfHameenlinna:feature/long-reservations
https://github.com/City-of-Helsinki/varaamo/compare/feature/helsinki-brand-v2...CityOfHameenlinna:feature/long-reservations 

Payments (rakennettu long reservationien päälle joten samat muutokset näkyvät näissä):
https://github.com/City-of-Helsinki/respa/compare/master...CityOfHameenlinna:feature/payments 
https://github.com/City-of-Helsinki/varaamo/compare/feature/helsinki-brand-v2...CityOfHameenlinna:feature/payments 

See specs for 1st phase #524

**Comment by tuomas777** [comment]
Some remarks:

* HML's actual payment processing code is meant to be implemented by subclassing `PaymentIntegration` class for each payment provider, which seems like a great clean way of doing that and something we should probably copy as close as possible. The current implementation includes only Paytrail integration, so we'll need to implement Bambora at least.

* HML's payment-related database models are based on multiday reservations, which is something we don't need yet (and specs of those are still unclear), and they seem to be pretty specific to HML's use cases in general, so we cannot use them exactly as they are.

* LPR implementation is tied tightly to only Ceepos, so we cannot use it as it is.

* If we need to use Ceepos, we could use LPR's code as an example.

**Comment by petterill** [comment]
We need to take into account that the most common way of implementing online payments for municipalities is by suomi.fi payments (Paytrail) integration. Paytrail does not offer a way to direct payments to the relevant party within a city (tiliöinti). So many municipalities will be using the Ceepos + Paytrail combo. Therefore, even if Helsinki might not need Ceepos integration, we should take this into account when planning architechture.
