### ISSUE TITLE
Opening hours are calculated incorrectly for exceptional periods

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/respa#75]
They are reported as being open even e.g. on christmas.

**Comment by Rikuoja** [comment]
http://api.hel.fi/respa/v1/resource/aurrojvtmt2a/?start=2015-12-25T00%3A00%3A00Z&end=2015-12-25T23%3A59%3A59Z

**Comment by juyrjola** [comment]
Also write tests for exception periods.

**Comment by Rikuoja** [comment]
Even more interestingly, resource and unit opening hours are reported differently for the exact same date in the same API call :D http://api.hel.fi/respa/v1/resource/aurrojvtmt2a/?start=2015-12-26T00%3A00%3A00Z&end=2015-12-26T23%3A59%3A59Z
