### ISSUE TITLE
Organization model for administrators and Unit objects

### ISSUE THREAD

**Issue by jussiarpalahti** [City-of-Helsinki/respa#9]
To separate admin rights for items, administrators and units should have organization as relation.

Through common organization, admins can only administrate their own items in the db.

Implement a foreign key in the unit model to an Organization model and link User model there.

Then user accounts can be associated with their necessary organizations and permission checking is possible. Use case: #8

**Comment by vikoivun** [comment]
A form of this is being implemented as issue #251
